version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ans_postgres
    environment:
      POSTGRES_DB: ans_db
      POSTGRES_USER: ans_user
      POSTGRES_PASSWORD: ans_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../data:/data
      - ../../sql:/sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ans_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
